# Generated by Django 2.0.1 on 2018-02-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='name',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tagline',
        ),
    ]
