# Generated by Django 2.0.1 on 2018-02-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpage', '0002_auto_20180228_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='blog',
            name='url',
            field=models.URLField(),
        ),
    ]
