# Generated by Django 2.0.1 on 2018-03-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpage', '0003_auto_20180228_1729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Urls',
        ),
    ]
