# Generated by Django 2.0.1 on 2018-03-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpage', '0004_auto_20180303_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('cookies_sape', models.CharField(max_length=20)),
                ('token_sape', models.CharField(max_length=20)),
                ('url_rota', models.CharField(max_length=20)),
                ('apikey_rota', models.CharField(max_length=20)),
                ('auth_blog', models.CharField(max_length=20)),
                ('iduser_blog', models.CharField(max_length=20)),
            ],
        ),
    ]
