# Generated by Django 2.0.1 on 2018-03-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpage', '0009_auto_20180306_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='cookies_sape',
            field=models.CharField(default='None', max_length=110),
        ),
    ]
