# Generated by Django 2.0.1 on 2018-03-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Isue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1, verbose_name='№')),
                ('id_isue', models.CharField(default='None', max_length=10, verbose_name='ID заявки')),
                ('type_isue', models.CharField(default='None', max_length=10, verbose_name='Тип заявки')),
                ('site_platform', models.CharField(default='None', max_length=40, verbose_name='Домен площадки')),
                ('date_create', models.DateTimeField(verbose_name='Дата создания')),
                ('anchor1', models.CharField(default='None', max_length=100, verbose_name='Анкор1')),
                ('anchor2', models.CharField(default='None', max_length=100, verbose_name='Анкор2')),
                ('anchor3', models.CharField(default='None', max_length=100, verbose_name='Анкор3')),
                ('anchor1_url', models.URLField(default='None', verbose_name='Ссылка анкора')),
                ('anchor1_text', models.CharField(default='None', max_length=40, verbose_name='Текст анкора')),
                ('blogun_isue_url', models.URLField(default='None', verbose_name='Урл заявки блогуна')),
                ('id_campaign_blogun', models.IntegerField(default=None, verbose_name='ID кампании блогуна')),
                ('check_url_blogun', models.URLField(default='None', verbose_name='Урл решения блогуна')),
                ('title_parse', models.CharField(default='None', max_length=100, verbose_name='Title')),
                ('keywords_parse', models.CharField(default='None', max_length=100, verbose_name='Keywords')),
                ('key_words', models.CharField(default='None', max_length=100, verbose_name='Ключевая фраза')),
                ('img_url', models.URLField(default='None', max_length=300, verbose_name='Урл картинки')),
                ('user_platform', models.CharField(default='None', max_length=40, verbose_name='Пользователь')),
                ('platform_name', models.CharField(default='None', max_length=40, verbose_name='Платформа')),
            ],
        ),
    ]
