# Generated by Django 2.0.1 on 2018-03-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0002_auto_20180314_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isue',
            name='check_url_blogun',
        ),
        migrations.AddField(
            model_name='isue',
            name='check_url_rota',
            field=models.URLField(default='None', verbose_name='Урл решения рота'),
        ),
        migrations.AlterField(
            model_name='isue',
            name='id_campaign_blogun',
            field=models.IntegerField(default=0, verbose_name='ID кампании блогуна'),
        ),
        migrations.AlterField(
            model_name='isue',
            name='ubdate_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
