# Generated by Django 2.0.1 on 2018-03-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0003_auto_20180315_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keys_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1, verbose_name='№')),
                ('roots', models.TextField(default='None', max_length=100, verbose_name='Корни слов')),
                ('image_text', models.CharField(default='None', max_length=100, verbose_name='Текст поиска картинки')),
            ],
        ),
    ]
