# Generated by Django 2.0.1 on 2018-03-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0004_keys_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys_list',
            name='key_words',
            field=models.TextField(default='None', max_length=100, verbose_name='Ключевая фраза'),
        ),
    ]
