# Generated by Django 2.0.1 on 2018-04-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0007_auto_20180406_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excludespage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_word', models.CharField(default='None', max_length=100, verbose_name='Исключающие страницу')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
        ),
    ]
