# Generated by Django 2.0.1 on 2018-04-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0009_auto_20180406_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='isue',
            name='public_content',
            field=models.TextField(default='None', verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='isue',
            name='public_url',
            field=models.TextField(default='None', verbose_name='Урл результата'),
        ),
    ]
