# Generated by Django 2.0.1 on 2018-05-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0011_auto_20180418_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys_list',
            name='length_of_key',
            field=models.IntegerField(default=1, verbose_name='Длина ключа'),
        ),
    ]
