# Generated by Django 2.0.1 on 2018-09-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0013_auto_20180603_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='isue',
            name='error_massage',
            field=models.CharField(default='None', max_length=250, verbose_name='Ошибка закрытия'),
        ),
        migrations.AlterField(
            model_name='isue',
            name='img_url',
            field=models.CharField(default='None', max_length=350, verbose_name='Урл картинки'),
        ),
        migrations.AlterField(
            model_name='isue',
            name='public_url',
            field=models.CharField(default='None', max_length=250, verbose_name='Урл результата'),
        ),
        migrations.AlterField(
            model_name='isue',
            name='status_isue',
            field=models.CharField(choices=[('Reword', 'REWORD'), ('Closed', 'CLOSED'), ('AddUnikal', 'ADDUNIKAL'), ('AddKey', 'ADDKEY'), ('New', 'NEW'), ('ErrorClosed', 'ERROR_CLOSED')], default='New', max_length=100, verbose_name='Статус заявки'),
        ),
    ]
