# Generated by Django 2.0.1 on 2019-02-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0014_auto_20180912_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_host', models.CharField(default='None', max_length=200, verbose_name='Адрес прокси')),
                ('num', models.IntegerField(default=1, verbose_name='№')),
            ],
        ),
    ]
